repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
    - id: black
      exclude: \.py-tpl$
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
        - black==24.2.0
        files: 'docs/.*\.txt$'
        args: ["--rst-literal-block"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
    - id: eslint
      name: eslint
      language: node
      additional_dependencies:
      - 'eslint@9.2.0'
      - '@eslint/js@9.2.0'
      - 'globals@15.2.0'
      entry: eslint
      types_or:
      - javascript
